
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 07 15:50:44 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DVOTACKA = 49;
  public static final int CONST = 6;
  public static final int CHAR = 21;
  public static final int GE = 31;
  public static final int CASE = 18;
  public static final int CONTINUE = 17;
  public static final int L = 32;
  public static final int G = 30;
  public static final int OROR = 35;
  public static final int DUGLASTA = 45;
  public static final int UPITNIK = 48;
  public static final int COMMA = 40;
  public static final int CLASS = 4;
  public static final int INC = 37;
  public static final int DIV = 26;
  public static final int ANDAND = 34;
  public static final int IF = 7;
  public static final int DOT = 41;
  public static final int LE = 33;
  public static final int EOF = 0;
  public static final int BOOLEAN = 22;
  public static final int RETURN = 14;
  public static final int LZAGRADA = 42;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 25;
  public static final int ADD = 23;
  public static final int NUMBER = 20;
  public static final int MOD = 27;
  public static final int NEQ = 29;
  public static final int BREAK = 3;
  public static final int IDENT = 19;
  public static final int VOID = 15;
  public static final int EQ = 28;
  public static final int TZ = 39;
  public static final int LVITICASTA = 46;
  public static final int SWITCH = 8;
  public static final int ELSE = 5;
  public static final int ENUM = 50;
  public static final int READ = 13;
  public static final int WHILE = 10;
  public static final int EXTENDS = 16;
  public static final int DODELA = 36;
  public static final int DEC = 38;
  public static final int DZAGRADA = 43;
  public static final int SUB = 24;
  public static final int LUGLASTA = 44;
  public static final int PRINT = 12;
  public static final int DO = 9;
  public static final int DVITICASTA = 47;
}

